config-version: 2
pack-downloader: true

settings:
    # These are commands that probably already exist on the average server
    # As of right now, this only applies to /report and /flyspeed
    disable-replaceable-commands: false
    # This unbinds /reload from reloading cocktail
    unbind-reload: false
    # Page length of reports
    # Warning: this setting isn't well tested, expect bugs and errors
    report-page-length: 5

datapack-urls:
    # New Formatting!
    # name of pack:
    #   url: "http://link.here"
    datapack:
        url: "https://github.com/Daily-Datapackers/datapack/archive/refs/heads/main.zip"
